[project]
name = "llm-model-zoo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "gradio>=6.5.1",
    "hf-transfer>=0.1.9",
    "huggingface-hub>=1.4.1",
    "numpy>=2.4.2",
    "pillow>=12.1.1",
    "pytorch-lightning>=2.6.5",
    "requests>=2.34.2",
    "safetensors>=0.7.0",
    "soundfile>=0.14.0",
    "torch>=2.10.0",
    "torchaudio>=2.11.0",
    "torchcodec>=0.16.0",
    "torchvision>=0.25.0",
    "transformers>=5.1.0",
]

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true


[tool.uv.sources]
torch = [
  { index = "pytorch-cu130", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
  { index = "pytorch-cu130", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
